# Selection and Pre-Processing
In this present notebook, we selected relevant columns, cleaned our database with regex and own functions and pre-processed texts with tokenization, removing stopwords and lemmatization.

✈️ We will use natural language processing techniques to apply machine learning algorithms to the data in next notebook.

## Selection

In [1]:
import pandas as pd
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..')))
from src import cleaning
from src import preprocessing

In [2]:
df = pd.read_csv("../data/00_amiai_raw_data.csv")
df.head()

,Carimbo de data/hora,Qual é o seu perfil de estudante?,O que te motivou a estudar Inteligência Artificial? (até 15 linhas)
0,27/03/2026 06:18:09,Graduação,Eu fui criado no interior. Meus estudos em tec...
1,27/03/2026 08:26:09,Graduação,Gosto de matemática e me considero bom nisso t...
2,27/03/2026 09:06:41,Pós-graduação,Meu interesse pela área de Inteligência Artifi...
3,27/03/2026 10:07:52,Pós-graduação,O que me motivou foi a ideia de desenvolver um...
4,27/03/2026 10:16:35,Pós-graduação,Desde a graduação sempre tive interesse em seg...

In [3]:
df = df.rename(columns={'O que te motivou a estudar Inteligência Artificial? (até 15 linhas)': 'background',
                        'Qual é o seu perfil de estudante?': 'student_profile',
                        'Carimbo de data/hora': 'date_time'})
df.head()

,date_time,student_profile,background
0,27/03/2026 06:18:09,Graduação,Eu fui criado no interior. Meus estudos em tec...
1,27/03/2026 08:26:09,Graduação,Gosto de matemática e me considero bom nisso t...
2,27/03/2026 09:06:41,Pós-graduação,Meu interesse pela área de Inteligência Artifi...
3,27/03/2026 10:07:52,Pós-graduação,O que me motivou foi a ideia de desenvolver um...
4,27/03/2026 10:16:35,Pós-graduação,Desde a graduação sempre tive interesse em seg...

## Cleaning

In [4]:
#quickly clean
df['background'] = cleaning.clean_text(df['background'])
df['background'] = df['background'].apply(lambda x: x.lower() if isinstance(x, str) else x)
df.head()

,date_time,student_profile,background
0,27/03/2026 06:18:09,Graduação,eu fui criado no interior meus estudos em tecn...
1,27/03/2026 08:26:09,Graduação,gosto de matematica e me considero bom nisso t...
2,27/03/2026 09:06:41,Pós-graduação,meu interesse pela area de inteligencia artifi...
3,27/03/2026 10:07:52,Pós-graduação,o que me motivou foi a ideia de desenvolver um...
4,27/03/2026 10:16:35,Pós-graduação,desde a graduacao sempre tive interesse em seg...

## Pre-Processing

In [5]:
df['tokens'] = df['background'].apply(preprocessing.tokenize)
df['tokens'] = df['tokens'].apply(preprocessing.remove_stopwords)
df['stems'] = df['tokens'].apply(preprocessing.stemming)
df['lemmas'] = df['background'].apply(preprocessing.lemmatization)

df.head()

,date_time,student_profile,background,tokens,stems,lemmas
0,27/03/2026 06:18:09,Graduação,eu fui criado no interior meus estudos em tecn...,"[criado, interior, estudos, tecnologia, inicio...","[cri, interi, estud, tecnolog, inici, quant, e...","[eu, ser, criar, em o, interior, meu, estudo, ..."
1,27/03/2026 08:26:09,Graduação,gosto de matematica e me considero bom nisso t...,"[gosto, matematica, considero, bom, nisso, qua...","[gost, matema, consider, bom, niss, quand, ini...","[gostar, de, matematica, e, eu, considerar, bo..."
2,27/03/2026 09:06:41,Pós-graduação,meu interesse pela area de inteligencia artifi...,"[interesse, area, inteligencia, artificial, ia...","[inter, are, inteligenc, artific, ia, despert,...","[meu, interesse, por o, areo, de, inteligencia..."
3,27/03/2026 10:07:52,Pós-graduação,o que me motivou foi a ideia de desenvolver um...,"[motivou, ideia, desenvolver, algoritmo, capaz...","[motiv, ide, desenvolv, algoritm, capaz, faz, ...","[o, que, eu, motivar, ser, o, ideia, de, desen..."
4,27/03/2026 10:16:35,Pós-graduação,desde a graduacao sempre tive interesse em seg...,"[desde, graduacao, sempre, interesse, seguir, ...","[desd, graduaca, sempr, inter, segu, are, acad...","[desde, o, graduacao, sempre, ter, interesse, ..."

In [7]:
df.to_csv('../data/01_amiai_preprocessed_data.csv')